---
openapi: 3.0.0
info:
  title: Planing purchase
  description: Api для сервиса построения планов закупок
  version: 2.0-oas3
servers:
- url: http://planning-purchase.local/api/v1
tags:
- name: api
  description: методы для построения планов закупок
paths:
  /wilson/create:
    post:
      tags:
      - api
      summary: Построение плана закупок.
      description: Модель Уилсона для построения плана закупок.
      operationId: api.wilson.create
      parameters:
      - name: freq_interval
        in: query
        description: Частота интервала у прогнозируемого периода, (1 день = 1D, 7 дней = 7D, 1 месяц = 1M).
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: service_level
        in: query
        required: true
        description: Уровень обслуживания, %.
        style: form
        explode: true
        schema:
          type: integer
      - name: storage_costs
        in: query
        description: Затраты на хранение продукции, ед.денежных средств.
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: float
      - name: product_price
        in: query
        required: true
        description: Стоимость единицы продукции, ед.денежных средств.
        style: form
        explode: true
        schema:
          type: number
          format: float
      - name: shipping_costs
        in: query
        description: Затраты на доставку продукции, ед.денежных средств.
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: float
      - name: time_shipping
        in: query
        description: Время доставки продукции, дни.
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: int32
      - name: delayed_deliveries
        in: query
        description: Задержка поставок, дни.
        style: form
        explode: true
        schema:
          type: number
          format: int32
      - name: production_quantity
        in: query
        description: Текущий уровень запасов, ед. продукции.
        style: form
        explode: true
        required: true
        schema:
          type: number
          format: int32
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
        "400":
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    Plan:
      type: object
      description: Результат создания модели Уилсона
      properties:
        size_order:
          type: number
          description: Размер заказа
          format: float
          example: 10
        total_costs:
          type: number
          description: Общие затраты
          format: float
          example: 3.5
        freq_delivery:
          type: number
          description: Периодичность достаки
          format: int32
          example: 2
        point_order:
          type: number
          description: Точка заказа
          format: int32
          example: 5
        reserve:
          type: number
          description: Страховой запас
          format: int32
          example: 2
        count_orders:
          type: number
          description: Количество заказов за период
          format: int32
          example: 10
        product_count:
          type: object
          description: Количество продукции за период
        orders_origin:
          description: Даты создания заказов
          type: object
        orders:
          description: Даты прибытия заказов
          type: object
        start_date:
          type: string
          description: Дата начала периода
          example: 2020-10-03
        end_date:
          type: string
          description: Дата конца периода
          example: 2020-11-03

    body:
      required:
      - file
      type: object
      properties:
        file:
          type: string
          description: Файл с информацией о продажах
          format: binary
    inline_response_400:
      properties:
        code:
          type: number
          format: int32
          example: 400
          description: Код ошибки
        message:
          type: string
          description: Сообщение ошибки